services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - 127.0.0.1:4000:8000
    environment:
      - SECRET_KEY=CHANGE_THIS_VALUE_IT_SHOULD_NOT_BE_PUBLIC
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=4
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=/var/log/CTFd/access.log
      - ERROR_LOG=/var/log/CTFd/error.log
      - PROBLEM_DOCKER_RUN_FOLDER=/home/docker
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
      - /home/docker:/home/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - frpc
    networks:
        default:
        internal:
        frp:
          ipv4_address: 10.1.0.5

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

  frps:
    build: ./frp
    restart: always
    volumes:
      - ./frp/conf:/conf/
    expose:
      - 80
    ports:
      - 20000-20099:20000-20099
    entrypoint:
      - /app/frps
      - -c
      - /conf/frps.toml
    networks:
      default:
      frp:
        ipv4_address: 10.1.0.3
  frpc:
    build: ./frp
    restart: always
    volumes:
      - ./frp/conf:/conf/
    expose:
      - 7400
    entrypoint:
      - /app/frpc
      - -c
      - /conf/frpc.toml
    networks:
      frp:
        ipv4_address: 10.1.0.4
      frp_containers:


networks:
    default:
      name: "ctfd_default"
    internal:
      name: "ctfd_internal"
      internal: true
    frp:
      name: "ctfd_frp"
      driver: bridge
      ipam:
        config:
          - subnet: 10.1.0.0/16
    frp_containers:
      name: "ctfd_frp_containers"
      driver: bridge
      ipam:
        config:
          - subnet: 10.2.0.0/16
